# Generated by Django 4.1.7 on 2023-04-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LicensePlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="license_plates/")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
