# Generated by Django 4.1.7 on 2023-04-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenseplate",
            name="plate_number",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("license_expiring_status", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                (
                    "license_plate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.licenseplate",
                    ),
                ),
            ],
        ),
    ]
